version: '3'
services:
  web:
    image: php:8.3.11-apache
    container_name: php8311apache
    ports:
      - "8888:80"
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
    networks:
      - con
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - con
  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 3306:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - con
networks:
  con: